
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: root
        url: jdbc:mysql://192.168.0.88:3306/test?useUnicode=true&characterEncoding=utf-8
        username: root
server:
    servlet:
        context-path: "/"